from __future__ import annotations

from techshort.domain.creative import Beat, BeatPlan, NarrativeBrief, derive_creative_id


def _beat(
    order: int,
    role: str,
    purpose: str,
    narration: str,
    text: str,
    visual: str,
    primitive: str,
    layout: str,
    animation: list[str],
    claims: list[str],
    seconds: float,
    evidence: list[str] | None = None,
) -> Beat:
    return Beat.model_validate(
        {
            "beat_id": f"beat-{order + 1:02d}",
            "order": order,
            "role": role,
            "purpose": purpose,
            "narration_guidance": narration,
            "on_screen_text": text,
            "visual_guidance": visual,
            "primitive_hint": primitive,
            "layout_family": layout,
            "animation_beats": animation,
            "claim_ids": claims,
            "evidence_span_ids": evidence or [],
            "approximate_duration": seconds,
        }
    )


def _surprising_result_beats() -> list[Beat]:
    return [
        _beat(
            0,
            "hook",
            "Open on the visual contradiction.",
            "Ask why a rotating blade can look curved.",
            "Straight, yet curved?",
            "Split the physical straight blade from the captured curved silhouette.",
            "BeforeAfterOverlay",
            "hero",
            ["show-straight", "reveal-curved", "hold-question"],
            ["claim-motion-skew", "claim-timing-interpretation"],
            7,
        ),
        _beat(
            1,
            "setup",
            "Separate appearance from physical shape.",
            "State that the image can reflect capture timing rather than a bent blade.",
            "Appearance ≠ shape",
            "Overlay a timing icon on the curved recording, leaving the real blade straight.",
            "KineticText",
            "split-comparison",
            ["label-object", "label-recording"],
            ["claim-timing-interpretation"],
            7,
        ),
        _beat(
            2,
            "mechanism",
            "Reveal successive row timing.",
            "Explain that rolling-shutter rows are recorded in sequence.",
            "Rows capture different moments",
            "Move a scanline down the sensor while the blade rotates slightly.",
            "RasterScan",
            "full-diagram",
            ["start-scan", "advance-time", "assemble-rows"],
            ["claim-row-timing", "claim-motion-skew"],
            11,
        ),
        _beat(
            3,
            "evidence",
            "Make one quantitative result visible.",
            "Walk through the source's 20 ms example and its approximately 2% lower-row offset.",
            "20 ms → about 2%",
            "Highlight the exact evidence excerpt, then map 0% and about 2% onto two sensor rows.",
            "EvidenceHighlight",
            "evidence-receipt",
            ["highlight-20-ms", "highlight-2-percent", "connect-to-grid"],
            ["claim-numeric-demo"],
            9,
            ["evidence-06"],
        ),
        _beat(
            4,
            "consequence",
            "Reconnect row timing to the strange shape.",
            "Show how faithful rows from different moments assemble into apparent curvature.",
            "Different moments, one frame",
            "Stack captured row slices until the curved silhouette is complete.",
            "GridWarp",
            "full-diagram",
            ["stack-top", "stack-middle", "stack-bottom", "reveal-result"],
            ["claim-motion-skew"],
            9,
        ),
        _beat(
            5,
            "tradeoff",
            "Name the timing alternative precisely.",
            "Contrast simultaneous global exposure with successive rolling capture.",
            "Together vs. in sequence",
            "Use matched grids: synchronized flash on the left, traveling scanline on the right.",
            "Comparison",
            "split-comparison",
            ["roll-scan", "global-flash", "compare-shapes"],
            ["claim-global", "claim-row-timing"],
            8,
        ),
        _beat(
            6,
            "limitation",
            "Prevent overgeneralization.",
            "Explain that other optical and processing effects can still alter geometry.",
            "One distortion solved—not all",
            "Dim the row-timing layer while listing the remaining documented effects as separate layers.",
            "LimitationCard",
            "limitation",
            ["resolve-row-skew", "reveal-other-effects"],
            ["claim-limitation"],
            8,
        ),
        _beat(
            7,
            "resolution",
            "Resolve the opening honestly.",
            "Return to the straight blade and label the curved image as a timing map.",
            "The image maps time",
            "Align scan time with the final curved silhouette; keep the real blade visibly straight.",
            "BeforeAfterOverlay",
            "hero",
            ["return-to-pair", "trace-time", "final-hold"],
            ["claim-timing-interpretation"],
            6,
        ),
    ]


def _everyday_mechanism_beats() -> list[Beat]:
    return [
        _beat(
            0,
            "hook",
            "Lead with an everyday scanner analogy.",
            "Invite the viewer to imagine scanning a page while it slides sideways.",
            "Scan while sliding",
            "A page moves right beneath a scanline traveling downward.",
            "RasterScan",
            "hero",
            ["start-page", "move-page", "start-scan"],
            ["claim-scan-analogy"],
            7,
        ),
        _beat(
            1,
            "consequence",
            "Show the analogy's assembled result early.",
            "Each line can be faithful even though the assembled page is skewed.",
            "Faithful lines. Skewed page.",
            "Stack individually straight line samples into a slanted page boundary.",
            "GridWarp",
            "full-diagram",
            ["capture-lines", "assemble-lines", "reveal-skew"],
            ["claim-scan-analogy", "claim-motion-skew"],
            8,
        ),
        _beat(
            2,
            "setup",
            "Map the scanner to the camera.",
            "Identify sensor rows as the lines read across a frame interval.",
            "Sensor rows are scan lines",
            "Morph paper lines into sensor rows without changing the scan direction.",
            "MechanismDiagram",
            "full-diagram",
            ["show-paper", "morph-to-sensor", "label-rows"],
            ["claim-row-timing", "claim-scan-analogy"],
            9,
        ),
        _beat(
            3,
            "mechanism",
            "Run the actual camera mechanism.",
            "Move an edge while successive sensor rows capture different moments.",
            "Motion + row time = skew",
            "A straight edge moves horizontally as the scanline descends; retain each captured sample.",
            "RasterScan",
            "full-diagram",
            ["move-edge", "scan-rows", "retain-samples", "assemble-frame"],
            ["claim-row-timing", "claim-motion-skew"],
            11,
        ),
        _beat(
            4,
            "evidence",
            "Ground the analogy in exact evidence.",
            "Show the documented sequential-row statement and the 20 ms worked example.",
            "20 ms readout",
            "Display a short source receipt, then annotate top 0% and bottom about 2%.",
            "SourceReceipt",
            "evidence-receipt",
            ["show-excerpt", "highlight-sequence", "reveal-values"],
            ["claim-row-timing", "claim-numeric-demo"],
            9,
            ["evidence-01", "evidence-06"],
        ),
        _beat(
            5,
            "tradeoff",
            "Expose the controllable parameters.",
            "Explain that faster motion or longer readout increases visible skew.",
            "More motion or time → more skew",
            "Use bounded sliders for readout time in ms and movement in percent of image width, with the grid skew responding.",
            "ParameterSimulation",
            "numeric-result",
            ["increase-motion", "increase-readout", "compare-skew"],
            ["claim-parameters"],
            8,
        ),
        _beat(
            6,
            "limitation",
            "Keep the mechanism scoped.",
            "State that reducing row skew does not guarantee undistorted geometry.",
            "This is one distortion",
            "Freeze the scanline, then reveal other documented geometry-changing effects outside it.",
            "LimitationCard",
            "limitation",
            ["freeze-scan", "reveal-other-effects"],
            ["claim-limitation"],
            8,
        ),
        _beat(
            7,
            "resolution",
            "Return to the transferable mental model.",
            "Conclude that a rolling-shutter frame is a small timeline assembled as one picture.",
            "One frame, many moments",
            "Collapse successive time-stamped rows into a single completed frame.",
            "Timeline",
            "hero",
            ["show-row-times", "collapse-timeline", "final-hold"],
            ["claim-row-timing", "claim-motion-skew"],
            6,
        ),
    ]


def _engineering_tradeoff_beats() -> list[Beat]:
    return [
        _beat(
            0,
            "hook",
            "Frame a precise timing comparison.",
            "Ask whether one frame represents one instant or a sequence of instants.",
            "One instant—or many?",
            "Place matched sensor grids under a single time ruler.",
            "Comparison",
            "hero",
            ["show-grids", "show-time-ruler", "pose-question"],
            ["claim-row-timing", "claim-global"],
            7,
        ),
        _beat(
            1,
            "setup",
            "Define rolling capture.",
            "Show rolling shutter recording rows successively over a readout interval.",
            "Rolling: rows in sequence",
            "A scanline travels down the rolling grid while a straight edge moves.",
            "RasterScan",
            "full-diagram",
            ["move-edge", "travel-scanline", "retain-rows"],
            ["claim-row-timing", "claim-motion-skew"],
            10,
        ),
        _beat(
            2,
            "setup",
            "Define global capture.",
            "Show global shutter exposing rows together and avoiding row-timing skew.",
            "Global: rows together",
            "Flash every row simultaneously on the matched grid; preserve the straight edge.",
            "MechanismDiagram",
            "full-diagram",
            ["arm-grid", "global-flash", "show-straight-result"],
            ["claim-global"],
            9,
        ),
        _beat(
            3,
            "evidence",
            "Quantify the rolling case.",
            "Use the source's 20 ms rolling-readout example and approximately 2% bottom-row offset.",
            "20 ms → about 2%",
            "Show exact evidence before annotating top and bottom offsets on the rolling grid.",
            "EvidenceHighlight",
            "evidence-receipt",
            ["show-source", "highlight-units", "map-offsets"],
            ["claim-numeric-demo"],
            9,
            ["evidence-06"],
        ),
        _beat(
            4,
            "tradeoff",
            "Compare only the documented timing behavior.",
            "Contrast successive and simultaneous row timing without inventing broader performance claims.",
            "Successive vs. simultaneous",
            "Synchronize both grids under the same moving edge and time ruler.",
            "Comparison",
            "split-comparison",
            ["run-rolling", "run-global", "compare-output"],
            ["claim-row-timing", "claim-global"],
            10,
        ),
        _beat(
            5,
            "consequence",
            "Show the parameter sensitivity.",
            "Explain that faster motion or longer readout makes rolling skew more visible.",
            "Motion × readout time",
            "Increase readout time in ms and movement in percent of image width one at a time; annotate the rolling result only.",
            "ParameterSimulation",
            "numeric-result",
            ["baseline", "increase-motion", "increase-readout"],
            ["claim-parameters"],
            8,
        ),
        _beat(
            6,
            "limitation",
            "Reject the perfect-camera inference.",
            "State that avoiding row-timing skew does not remove other documented distortions.",
            "No perfect-image guarantee",
            "Keep global's straight timing result but add separate layers for blur, lens, stabilization, and processing.",
            "LimitationCard",
            "limitation",
            ["hold-timing-result", "add-other-layers"],
            ["claim-limitation"],
            9,
        ),
        _beat(
            7,
            "resolution",
            "Close on the engineering distinction.",
            "Summarize rolling as a time sequence and global as one shared exposure instant.",
            "Sequence vs. shared instant",
            "Resolve the time ruler into two compact timing diagrams, not a winner badge.",
            "Timeline",
            "split-comparison",
            ["compress-rolling-times", "align-global-time", "final-hold"],
            ["claim-row-timing", "claim-global"],
            6,
        ),
    ]


def build_rolling_shutter_beat_plan(brief: NarrativeBrief) -> BeatPlan:
    """Return a complete editorial spine whose order changes with the selected angle."""
    if brief.angle == "surprising-result":
        beats = _surprising_result_beats()
    elif brief.angle == "everyday-mechanism":
        beats = _everyday_mechanism_beats()
    else:
        beats = _engineering_tradeoff_beats()
    payload: dict[str, object] = {
        "narrative_brief_version_id": brief.version_id,
        "claims_version_id": brief.claims_version_id,
        "angle": brief.angle,
        "factual_locks": brief.factual_locks,
        "beats": beats,
    }
    payload["version_id"] = derive_creative_id("beats", payload)
    return BeatPlan.model_validate(payload)
