from __future__ import annotations

from techshort.domain.creative import Beat, BeatPlan, NarrativeBrief, derive_creative_id
from techshort.domain.models import AngleKind


def _beat(
    order: int,
    role: str,
    purpose: str,
    narration: str,
    text: str,
    visual: str,
    primitive: str,
    layout: str,
    animation: list[str],
    claims: list[str],
    seconds: float,
    evidence: list[str] | None = None,
) -> Beat:
    return Beat.model_validate(
        {
            "beat_id": f"beat-{order + 1:02d}",
            "order": order,
            "role": role,
            "purpose": purpose,
            "narration_guidance": narration,
            "on_screen_text": text,
            "visual_guidance": visual,
            "primitive_hint": primitive,
            "layout_family": layout,
            "animation_beats": animation,
            "claim_ids": claims,
            "evidence_span_ids": evidence or [],
            "approximate_duration": seconds,
        }
    )


def _surprising_result_beats() -> list[Beat]:
    return [
        _beat(
            0,
            "hook",
            "Open on the visual contradiction.",
            "Ask why a rotating blade can look curved.",
            "Straight, yet curved?",
            "Split the physical straight blade from the captured curved silhouette.",
            "BeforeAfterOverlay",
            "hero",
            ["show-straight", "reveal-curved", "hold-question"],
            ["claim-motion-skew", "claim-timing-interpretation"],
            5,
        ),
        _beat(
            1,
            "setup",
            "Establish sequential row capture.",
            "State that rolling shutter records sensor rows at successive moments.",
            "Rows, not one instant",
            "Reveal one row at a time beside a descending timing marker.",
            "KineticText",
            "split-comparison",
            ["reveal-rows", "advance-time"],
            ["claim-row-timing"],
            7,
        ),
        _beat(
            2,
            "mechanism",
            "Reveal successive row timing.",
            "Explain that rolling-shutter rows are recorded in sequence.",
            "Rows capture different moments",
            "Move a scanline down the sensor while the blade rotates slightly.",
            "RasterScan",
            "full-diagram",
            ["start-scan", "advance-time", "assemble-rows"],
            ["claim-row-timing", "claim-motion-skew"],
            7,
        ),
        _beat(
            3,
            "evidence",
            "Make one quantitative result visible.",
            "Walk through the source's 20 ms example and its approximately 2% lower-row offset.",
            "20 ms → about 2%",
            "Highlight the exact evidence excerpt, then map 0% and about 2% onto two sensor rows.",
            "EvidenceHighlight",
            "evidence-receipt",
            ["highlight-20-ms", "highlight-2-percent", "connect-to-grid"],
            ["claim-numeric-demo"],
            7,
            ["evidence-06"],
        ),
        _beat(
            4,
            "re-hook",
            "Correct the likely physical-bending misconception.",
            "Ask whether the blade bent or the frame mapped motion across time.",
            "Did the blade bend?",
            "Stack captured row slices until the curved silhouette is complete.",
            "GridWarp",
            "full-diagram",
            ["stack-top", "stack-middle", "stack-bottom", "reveal-result"],
            ["claim-motion-skew", "claim-timing-interpretation"],
            6,
        ),
        _beat(
            5,
            "re-hook",
            "Pivot from mechanism to the controllable timing comparison.",
            "Ask what changes the skew before contrasting simultaneous and successive capture.",
            "What changes the effect?",
            "Use matched grids: synchronized flash on the left, traveling scanline on the right.",
            "Comparison",
            "split-comparison",
            ["roll-scan", "global-flash", "compare-shapes"],
            ["claim-parameters", "claim-global", "claim-row-timing"],
            7,
        ),
        _beat(
            6,
            "limitation",
            "Prevent overgeneralization.",
            "Explain that other optical and processing effects can still alter geometry.",
            "One distortion solved—not all",
            "Dim the row-timing layer while listing the remaining documented effects as separate layers.",
            "LimitationCard",
            "limitation",
            ["resolve-row-skew", "reveal-other-effects"],
            ["claim-limitation"],
            7,
        ),
        _beat(
            7,
            "resolution",
            "Resolve the opening honestly.",
            "Return to the straight blade and label the curved image as a timing map.",
            "The image maps time",
            "Align scan time with the final curved silhouette; keep the real blade visibly straight.",
            "BeforeAfterOverlay",
            "hero",
            ["return-to-pair", "trace-time", "final-hold"],
            ["claim-timing-interpretation"],
            6,
        ),
    ]


def _everyday_mechanism_beats() -> list[Beat]:
    return [
        _beat(
            0,
            "hook",
            "Lead with an everyday scanner analogy.",
            "Invite the viewer to imagine scanning a page while it slides sideways.",
            "Scan while sliding",
            "A page moves right beneath a scanline traveling downward.",
            "RasterScan",
            "hero",
            ["start-page", "move-page", "start-scan"],
            ["claim-row-timing", "claim-scan-analogy"],
            5,
        ),
        _beat(
            1,
            "mechanism",
            "Establish sequential sensor-row capture.",
            "Show neighboring sensor rows recording successive instants.",
            "Rows read in sequence",
            "Move a timing marker from the top sensor row toward the bottom row.",
            "MechanismDiagram",
            "full-diagram",
            ["show-top-row", "advance-marker", "show-bottom-row"],
            ["claim-row-timing"],
            7,
        ),
        _beat(
            2,
            "consequence",
            "Show the moving-page analogy's assembled result.",
            "Each scanned line can be faithful even though the assembled page is skewed.",
            "Faithful lines. Skewed page.",
            "Stack individually straight line samples into a slanted page boundary.",
            "GridWarp",
            "full-diagram",
            ["capture-lines", "assemble-lines", "reveal-skew"],
            ["claim-scan-analogy", "claim-motion-skew"],
            7,
        ),
        _beat(
            3,
            "evidence",
            "Ground the analogy in exact evidence.",
            "Show the documented sequential-row statement and the 20 ms worked example.",
            "20 ms → about 2%",
            "Display a short source receipt, then annotate top 0% and bottom about 2%.",
            "SourceReceipt",
            "evidence-receipt",
            ["show-excerpt", "highlight-sequence", "reveal-values"],
            ["claim-row-timing", "claim-numeric-demo"],
            7,
            ["evidence-01", "evidence-06"],
        ),
        _beat(
            4,
            "re-hook",
            "Turn the evidence into a bounded parameter question.",
            "Ask what controls how far the rows drift during readout.",
            "Motion (% width) + readout (ms)",
            "Use source-bounded controls: movement in percent of image width and readout in ms.",
            "ParameterSimulation",
            "numeric-result",
            ["pose-question", "reveal-motion", "reveal-readout"],
            ["claim-parameters", "claim-row-timing", "claim-numeric-demo"],
            6,
        ),
        _beat(
            5,
            "re-hook",
            "Pivot from parameters to the documented timing alternative.",
            "Ask whether exposing every row together changes this specific skew.",
            "Would shared timing change it?",
            "Compare bounded rolling-shutter parameters with one simultaneous global exposure.",
            "Comparison",
            "split-comparison",
            ["increase-motion", "increase-readout", "global-flash"],
            ["claim-parameters", "claim-global"],
            7,
        ),
        _beat(
            6,
            "limitation",
            "Keep the mechanism scoped.",
            "State that reducing row skew does not guarantee undistorted geometry.",
            "This is one distortion",
            "Freeze the scanline, then reveal other documented geometry-changing effects outside it.",
            "LimitationCard",
            "limitation",
            ["freeze-scan", "reveal-other-effects"],
            ["claim-limitation"],
            7,
        ),
        _beat(
            7,
            "resolution",
            "Return to the transferable mental model.",
            "Conclude that a rolling-shutter frame is a small timeline assembled as one picture.",
            "One frame, many moments",
            "Collapse successive time-stamped rows into a single completed frame.",
            "MechanismDiagram",
            "hero",
            ["show-row-times", "collapse-timeline", "final-hold"],
            ["claim-row-timing", "claim-motion-skew"],
            6,
        ),
    ]


def _engineering_tradeoff_beats() -> list[Beat]:
    return [
        _beat(
            0,
            "hook",
            "Frame a precise timing comparison.",
            "Ask whether one frame represents one instant or a sequence of instants.",
            "One instant—or many?",
            "Place matched sensor grids under a single time ruler.",
            "Comparison",
            "hero",
            ["show-grids", "show-time-ruler", "pose-question"],
            ["claim-row-timing", "claim-global"],
            5,
        ),
        _beat(
            1,
            "setup",
            "Define rolling capture.",
            "Show rolling shutter recording rows successively over a readout interval.",
            "Rolling: rows in sequence",
            "A scanline travels down the rolling grid while a straight edge moves.",
            "RasterScan",
            "full-diagram",
            ["move-edge", "travel-scanline", "retain-rows"],
            ["claim-row-timing"],
            7,
        ),
        _beat(
            2,
            "consequence",
            "Show how motion changes successive row samples.",
            "Show successive rows capturing different positions during motion.",
            "Motion changes each row",
            "Move a straight edge while the scanline descends, then assemble the retained samples.",
            "RasterScan",
            "full-diagram",
            ["move-edge", "scan-rows", "assemble-result"],
            ["claim-motion-skew"],
            7,
        ),
        _beat(
            3,
            "evidence",
            "Quantify the rolling case.",
            "Use the source's 20 ms rolling-readout example and approximately 2% bottom-row offset.",
            "20 ms → about 2%",
            "Show exact evidence before annotating top and bottom offsets on the rolling grid.",
            "ChartReveal",
            "evidence-receipt",
            ["show-axes", "reveal-offset-line", "label-endpoint"],
            ["claim-numeric-demo"],
            7,
            ["evidence-06"],
        ),
        _beat(
            4,
            "re-hook",
            "Correct the inference that simultaneous exposure solves every distortion.",
            "Ask whether avoiding row-timing skew guarantees undistorted geometry.",
            "Does global solve everything?",
            "Synchronize both grids under the same moving edge and time ruler.",
            "Comparison",
            "split-comparison",
            ["run-rolling", "run-global", "compare-output"],
            ["claim-global", "claim-limitation"],
            6,
        ),
        _beat(
            5,
            "re-hook",
            "Pivot from design comparison to controllable parameters.",
            "Ask what engineers can change in the rolling timing case.",
            "Change motion (%) or readout (ms)?",
            "Increase readout time in ms and movement in percent of image width one at a time; annotate the rolling result only.",
            "ParameterSimulation",
            "numeric-result",
            ["baseline", "increase-motion", "increase-readout"],
            ["claim-parameters", "claim-global", "claim-numeric-demo"],
            7,
        ),
        _beat(
            6,
            "limitation",
            "Reject the perfect-camera inference.",
            "State that avoiding row-timing skew does not remove other documented distortions.",
            "No perfect-image guarantee",
            "Keep global's straight timing result but add separate layers for blur, lens, stabilization, and processing.",
            "LimitationCard",
            "limitation",
            ["hold-timing-result", "add-other-layers"],
            ["claim-limitation"],
            7,
        ),
        _beat(
            7,
            "resolution",
            "Close on the engineering distinction.",
            "Summarize rolling as a time sequence and global as one shared exposure instant.",
            "Sequence vs. shared instant",
            "Resolve the time ruler into two compact timing diagrams, not a winner badge.",
            "BeforeAfterOverlay",
            "split-comparison",
            ["compress-rolling-times", "align-global-time", "final-hold"],
            ["claim-row-timing", "claim-global", "claim-limitation"],
            6,
        ),
    ]


def rolling_shutter_beats(angle: AngleKind) -> list[Beat]:
    """Return the angle-specific fixture beats shared by planning and storyboarding."""
    if angle == "surprising-result":
        return _surprising_result_beats()
    if angle == "everyday-mechanism":
        return _everyday_mechanism_beats()
    return _engineering_tradeoff_beats()


def build_rolling_shutter_beat_plan(brief: NarrativeBrief) -> BeatPlan:
    """Return a complete editorial spine whose order changes with the selected angle."""
    beats = rolling_shutter_beats(brief.angle)
    payload: dict[str, object] = {
        "narrative_brief_version_id": brief.version_id,
        "claims_version_id": brief.claims_version_id,
        "angle": brief.angle,
        "factual_locks": brief.factual_locks,
        "beats": beats,
    }
    payload["version_id"] = derive_creative_id("beats", payload)
    return BeatPlan.model_validate(payload)
